#!/usr/bin/env bash
#
# Generate the .env docker-compose reads its secrets from: a random DB password and the JWT secret
# the backend signs/verifies its tokens with. Run this once, before `docker compose up -d`.
#
set -euo pipefail
cd "$(dirname "$0")"

if [ -f .env ]; then
    echo "refusing to overwrite an existing .env (delete it yourself to regenerate secrets)" >&2
    exit 1
fi

# No openssl dependency: draw from /dev/urandom and keep only URL/JSON-safe characters.
secret() { (set +o pipefail; LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$1"); }

cat > .env <<EOF
# Generated by gen-env.sh — contains secrets. Never commit or share. Keep it next to
# docker-compose.yml. Regenerating invalidates every existing login (the JWT secret changes).
POSTGRES_USER=ccproxy
POSTGRES_DB=ccproxy
POSTGRES_PASSWORD=$(secret 40)
JWT_SECRET=$(secret 64)
# The platform operator's login password (super-admin). Read it back from this file to log in.
SUPERADMIN_PASSWORD=$(secret 24)
# Shared secret the backend and the proxy-engine authenticate their control channel with.
ENGINE_SECRET=$(secret 40)

# Host port the gateway (nginx) listens on. Put your TLS-terminating reverse proxy in front of it.
NGINX_HTTP_PORT=80
EOF
chmod 600 .env

mkdir -p app_data/postgresql keys

# The operator SSH keypair used for provisioning: the tenant injects the PUBLIC key into each machine
# and the backend uses the PRIVATE key to SSH in (install CA, set proxy, drive /login). Generated
# here so provisioning needs no manual configuration; ./keys is mounted read-only at /keys.
if [ ! -f keys/operator ]; then
    ssh-keygen -t ed25519 -N '' -C ccproxy-operator -f keys/operator >/dev/null
    echo "Generated operator provisioning keypair at ./keys/operator(.pub)."
fi

# The MITM CA the proxy-engine signs per-domain leaf certs with, and that machines must trust. The
# backend serves ca.crt (/ccproxy/provisioning/ca-cert) and installs it over SSH during provisioning.
if [ ! -f keys/ca.key ]; then
    openssl genrsa -out keys/ca.key 2048 >/dev/null 2>&1
    openssl req -x509 -new -nodes -key keys/ca.key -sha256 -days 3650 \
        -out keys/ca.crt -subj '/CN=CCProxy MITM CA' >/dev/null 2>&1
    echo "Generated MITM CA at ./keys/ca.crt (+ ca.key)."
fi

echo "Wrote .env (chmod 600) and created app_data/ + keys/ directories."
echo "Next: docker compose up -d   then   docker compose ps   (wait for every service 'healthy')."
