/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.24.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.ccproxy.api

import app.microteams.ccproxy.model.AccountDTO
import app.microteams.ccproxy.model.AccountStatusDTO
import app.microteams.ccproxy.model.CreateAccountRequestDTO
import app.microteams.ccproxy.model.ErrorDTO
import app.microteams.ccproxy.model.ListAccountsResponseDTO
import app.microteams.ccproxy.model.SetSetupTokenRequestDTO
import app.microteams.ccproxy.model.SetupTokenStatusDTO
import app.microteams.ccproxy.model.UpdateAccountRequestDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface AccountApi {

    @Operation(
        tags = ["account"],
        summary = "Add an Anthropic account to the pool",
        operationId = "createAccount",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = AccountDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        // "/account"
        value = [PATH_CREATE_ACCOUNT],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createAccount(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createAccountRequestDTO: CreateAccountRequestDTO
    ): ResponseEntity<AccountDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["account"],
        summary = "Remove an account (must have no machines bound)",
        operationId = "deleteAccount",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
                ApiResponse(
                    responseCode = "409",
                    description = "Conflict (precondition not met)",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        // "/account/{id}"
        value = [PATH_DELETE_ACCOUNT],
        produces = ["application/json"],
    )
    fun deleteAccount(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["account"],
        summary = "Clear this account's setup-token (future logins revert to interactive /login)",
        operationId = "deleteAccountSetupToken",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        // "/account/{id}/setup-token"
        value = [PATH_DELETE_ACCOUNT_SETUP_TOKEN],
        produces = ["application/json"],
    )
    fun deleteAccountSetupToken(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["account"],
        summary = "",
        operationId = "getAccount",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = AccountDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        // "/account/{id}"
        value = [PATH_GET_ACCOUNT],
        produces = ["application/json"],
    )
    fun getAccount(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<AccountDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["account"],
        summary =
            "Whether this account has a setup-token + its expiry (never returns the token itself)",
        operationId = "getAccountSetupToken",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = SetupTokenStatusDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        // "/account/{id}/setup-token"
        value = [PATH_GET_ACCOUNT_SETUP_TOKEN],
        produces = ["application/json"],
    )
    fun getAccountSetupToken(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<SetupTokenStatusDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["account"],
        summary = "List accounts in the pool",
        operationId = "listAccounts",
        description = """Tokens are never here — accounts hold none.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListAccountsResponseDTO::class))],
                )
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        // "/account"
        value = [PATH_LIST_ACCOUNTS],
        produces = ["application/json"],
    )
    fun listAccounts(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
        @Parameter(description = "", schema = Schema(allowableValues = ["active", "disabled"]))
        @Valid
        @RequestParam(value = "status", required = false)
        status: AccountStatusDTO?,
    ): ResponseEntity<ListAccountsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["account"],
        summary =
            "Set/replace this account's OAuth setup-token — machines then activate without /login",
        operationId = "setAccountSetupToken",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = SetupTokenStatusDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.PUT],
        // "/account/{id}/setup-token"
        value = [PATH_SET_ACCOUNT_SETUP_TOKEN],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun setAccountSetupToken(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        setSetupTokenRequestDTO: SetSetupTokenRequestDTO,
    ): ResponseEntity<SetupTokenStatusDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["account"],
        summary = "Edit email / proxy / remark / status",
        operationId = "updateAccount",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = AccountDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        // "/account/{id}"
        value = [PATH_UPDATE_ACCOUNT],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun updateAccount(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        updateAccountRequestDTO: UpdateAccountRequestDTO,
    ): ResponseEntity<AccountDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    companion object {
        // for your own safety never directly reuse these path definitions in tests
        const val PATH_CREATE_ACCOUNT: String = "/account"
        const val PATH_DELETE_ACCOUNT: String = "/account/{id}"
        const val PATH_DELETE_ACCOUNT_SETUP_TOKEN: String = "/account/{id}/setup-token"
        const val PATH_GET_ACCOUNT: String = "/account/{id}"
        const val PATH_GET_ACCOUNT_SETUP_TOKEN: String = "/account/{id}/setup-token"
        const val PATH_LIST_ACCOUNTS: String = "/account"
        const val PATH_SET_ACCOUNT_SETUP_TOKEN: String = "/account/{id}/setup-token"
        const val PATH_UPDATE_ACCOUNT: String = "/account/{id}"
    }
}
