/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.ccproxy.api

import app.microteams.ccproxy.model.AccountDTO
import app.microteams.ccproxy.model.AccountStatusDTO
import app.microteams.ccproxy.model.CreateAccountRequestDTO
import app.microteams.ccproxy.model.ErrorDTO
import app.microteams.ccproxy.model.ListAccountsResponseDTO
import app.microteams.ccproxy.model.UpdateAccountRequestDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface AccountApi {

    @Operation(
        tags = ["account"],
        summary = "Add an Anthropic account to the pool",
        operationId = "createAccount",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = AccountDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/account"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createAccount(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createAccountRequestDTO: CreateAccountRequestDTO
    ): ResponseEntity<AccountDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["account"],
        summary = "Remove an account (must have no machines bound)",
        operationId = "deleteAccount",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
                ApiResponse(
                    responseCode = "409",
                    description = "Conflict (precondition not met)",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/account/{id}"],
        produces = ["application/json"],
    )
    fun deleteAccount(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["account"],
        summary = "",
        operationId = "getAccount",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = AccountDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/account/{id}"],
        produces = ["application/json"],
    )
    fun getAccount(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<AccountDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["account"],
        summary = "List accounts in the pool",
        operationId = "listAccounts",
        description = """Tokens are never here — accounts hold none.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListAccountsResponseDTO::class))],
                )
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/account"],
        produces = ["application/json"],
    )
    fun listAccounts(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
        @Parameter(description = "", schema = Schema(allowableValues = ["active", "disabled"]))
        @Valid
        @RequestParam(value = "status", required = false)
        status: AccountStatusDTO?,
    ): ResponseEntity<ListAccountsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["account"],
        summary = "Edit email / proxy / remark / status",
        operationId = "updateAccount",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = AccountDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/account/{id}"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun updateAccount(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        updateAccountRequestDTO: UpdateAccountRequestDTO,
    ): ResponseEntity<AccountDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
