/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.ccproxy.api

import app.microteams.ccproxy.model.ErrorDTO
import app.microteams.ccproxy.model.ListLoginRequestsResponseDTO
import app.microteams.ccproxy.model.LoginRequestDTO
import app.microteams.ccproxy.model.LoginRequestStatusDTO
import app.microteams.ccproxy.model.SubmitLoginCodeRequestDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface LoginRequestApi {

    @Operation(
        tags = ["loginRequest"],
        summary = "Abandon an in-flight login (kills the tmux session)",
        operationId = "cancelLoginRequest",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = LoginRequestDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security =
            [
                SecurityRequirement(name = "tenantSecret"),
                SecurityRequirement(name = "loginOperatorSecret"),
                SecurityRequirement(name = "superAdmin"),
            ],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/login-request/{id}/cancel"],
        produces = ["application/json"],
    )
    fun cancelLoginRequest(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<LoginRequestDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["loginRequest"],
        summary = "",
        operationId = "getLoginRequest",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = LoginRequestDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security =
            [
                SecurityRequirement(name = "loginOperatorSecret"),
                SecurityRequirement(name = "superAdmin"),
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/login-request/{id}"],
        produces = ["application/json"],
    )
    fun getLoginRequest(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<LoginRequestDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["loginRequest"],
        summary = "List login-requests",
        operationId = "listLoginRequests",
        description =
            """The login-operator's queue. Default lists actionable ones (`awaiting-code`). Each item carries the machine + account context (email, upstream proxy, remark) and, once ready, the OAuth URL to open. IMPORTANT for the operator: open that URL in a browser sent through the account's `proxy`, so the login IP matches the API egress IP. Super-admin sees all; a login-operator sees the global queue.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema =
                                    Schema(implementation = ListLoginRequestsResponseDTO::class)
                            )
                        ],
                )
            ],
        security =
            [
                SecurityRequirement(name = "loginOperatorSecret"),
                SecurityRequirement(name = "superAdmin"),
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/login-request"],
        produces = ["application/json"],
    )
    fun listLoginRequests(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
        @Parameter(
            description = "filter by status; defaults to awaiting-code",
            schema =
                Schema(
                    allowableValues =
                        [
                            "preparing",
                            "awaitingCode",
                            "applying",
                            "completed",
                            "failed",
                            "expired",
                            "cancelled",
                        ]
                ),
        )
        @Valid
        @RequestParam(value = "status", required = false)
        status: LoginRequestStatusDTO?,
    ): ResponseEntity<ListLoginRequestsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["loginRequest"],
        summary = "Submit the real authorization code obtained from the browser",
        operationId = "submitLoginCode",
        description =
            """The operator, after authenticating as the account in the browser, pastes the real authorization code here (as `code` and `state`, or the combined `code#state`). The backend saves the real code, generates a FAKE code, drives the waiting Claude Code (in the machine's tmux) to paste it, and the proxy-engine swaps fake→real on the wire — capturing the real tokens and handing the machine fake ones. On success the request lands `completed` and the machine becomes `ready`. Never returns any token.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = LoginRequestDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
                ApiResponse(
                    responseCode = "409",
                    description = "request not awaiting a code",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "loginOperatorSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/login-request/{id}/code"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun submitLoginCode(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        submitLoginCodeRequestDTO: SubmitLoginCodeRequestDTO,
    ): ResponseEntity<LoginRequestDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
