/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.ccproxy.api

import app.microteams.ccproxy.model.CreateLoginOperatorRequestDTO
import app.microteams.ccproxy.model.CreateSecretRequestDTO
import app.microteams.ccproxy.model.CreateSecretResponseDTO
import app.microteams.ccproxy.model.ErrorDTO
import app.microteams.ccproxy.model.ListAuthSecretsResponseDTO
import app.microteams.ccproxy.model.ListLoginOperatorsResponseDTO
import app.microteams.ccproxy.model.LoginOperatorDTO
import app.microteams.ccproxy.model.UpdateLoginOperatorRequestDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface LoginOperatorApi {

    @Operation(
        tags = ["loginOperator"],
        summary = "Create a login-operator",
        operationId = "createLoginOperator",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = LoginOperatorDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/login-operator"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createLoginOperator(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createLoginOperatorRequestDTO: CreateLoginOperatorRequestDTO
    ): ResponseEntity<LoginOperatorDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["loginOperator"],
        summary = "",
        operationId = "createLoginOperatorSecret",
        description = """Mint a secret for the login-operator; plaintext returned ONCE.""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content =
                        [Content(schema = Schema(implementation = CreateSecretResponseDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/login-operator/{id}/secret"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createLoginOperatorSecret(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createSecretRequestDTO: CreateSecretRequestDTO,
    ): ResponseEntity<CreateSecretResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["loginOperator"],
        summary = "",
        operationId = "deleteLoginOperator",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/login-operator/{id}"],
        produces = ["application/json"],
    )
    fun deleteLoginOperator(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["loginOperator"],
        summary = "",
        operationId = "getLoginOperator",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = LoginOperatorDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/login-operator/{id}"],
        produces = ["application/json"],
    )
    fun getLoginOperator(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<LoginOperatorDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["loginOperator"],
        summary = "List a login-operator's secrets (metadata only)",
        operationId = "listLoginOperatorSecrets",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema = Schema(implementation = ListAuthSecretsResponseDTO::class)
                            )
                        ],
                )
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/login-operator/{id}/secret"],
        produces = ["application/json"],
    )
    fun listLoginOperatorSecrets(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<ListAuthSecretsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["loginOperator"],
        summary = "List login-operators",
        operationId = "listLoginOperators",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema =
                                    Schema(implementation = ListLoginOperatorsResponseDTO::class)
                            )
                        ],
                )
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/login-operator"],
        produces = ["application/json"],
    )
    fun listLoginOperators(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListLoginOperatorsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["loginOperator"],
        summary = "",
        operationId = "revokeLoginOperatorSecret",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/login-operator/{id}/secret/{secretId}"],
        produces = ["application/json"],
    )
    fun revokeLoginOperatorSecret(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @PathVariable("secretId")
        secretId: kotlin.Long,
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["loginOperator"],
        summary = "Rename or suspend a login-operator",
        operationId = "updateLoginOperator",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = LoginOperatorDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/login-operator/{id}"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun updateLoginOperator(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        updateLoginOperatorRequestDTO: UpdateLoginOperatorRequestDTO,
    ): ResponseEntity<LoginOperatorDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
