/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.ccproxy.api

import app.microteams.ccproxy.model.CreateMachineRequestDTO
import app.microteams.ccproxy.model.ErrorDTO
import app.microteams.ccproxy.model.ListMachinesResponseDTO
import app.microteams.ccproxy.model.ListUsageResponseDTO
import app.microteams.ccproxy.model.LoginRequestDTO
import app.microteams.ccproxy.model.MachineDTO
import app.microteams.ccproxy.model.MachineStatusDTO
import app.microteams.ccproxy.model.RebindAccountRequestDTO
import app.microteams.ccproxy.model.UpdateMachineRequestDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface MachineApi {

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "createMachine",
        description =
            """Register a machine. Every machine is driven by an on-machine connector that dials OUT to the control plane. Provide a `host` and the backend BOOTSTRAPS it: it SSHes in exactly once (the tenant must have injected the CCProxy SSH public key first — see /provisioning/ssh-pubkey) to install the connector and dial it back in — after which all config + login go over the connector, never SSH. Omit `host` for a machine the operator installs by hand: the response carries a `deviceToken` + `installCommand` to run on it. Creation returns immediately with status `provisioning`, landing `awaiting-login` once the connector is online (`online:true`). CCProxy binds the machine to an account internally (invisible to the tenant); the per-machine proxy/device credentials are secret and set on the machine, not returned in a list/get.""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = MachineDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
                ApiResponse(
                    responseCode = "409",
                    description = "no account available in the pool to bind",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/machine"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createMachine(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createMachineRequestDTO: CreateMachineRequestDTO
    ): ResponseEntity<MachineDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Tear a machine down (drops its proxy mapping and fake↔real credential)",
        operationId = "deleteMachine",
        description =
            """Revocation is confirmed, not best-effort: a 204 means the proxy-engine no longer serves this machine's session AND its durable credential is gone, so the machine's fake token can never spend again — including across engine restarts. If the engine cannot confirm dropping the live session, the call fails with 502 and NOTHING is deleted; retry until you get the 204. Only this machine's credential is touched; every other machine is unaffected.""",
        responses =
            [
                ApiResponse(
                    responseCode = "204",
                    description = "No Content — the credential is verifiably revoked",
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
                ApiResponse(
                    responseCode = "502",
                    description =
                        "proxy-engine did not confirm the revocation; nothing was deleted — retry",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/machine/{id}"],
        produces = ["application/json"],
    )
    fun deleteMachine(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Get a machine (status, proxy config, credential expiry, current login)",
        operationId = "getMachine",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = MachineDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security =
            [SecurityRequirement(name = "tenantSecret"), SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/{id}"],
        produces = ["application/json"],
    )
    fun getMachine(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<MachineDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Usage records for one machine",
        operationId = "getMachineUsage",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListUsageResponseDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security =
            [SecurityRequirement(name = "tenantSecret"), SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/{id}/usage"],
        produces = ["application/json"],
    )
    fun getMachineUsage(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
        @Parameter(description = "lower time bound (epoch seconds), inclusive")
        @Valid
        @RequestParam(value = "since", required = false)
        since: kotlin.Long?,
        @Parameter(description = "upper time bound (epoch seconds), exclusive")
        @Valid
        @RequestParam(value = "until", required = false)
        until: kotlin.Long?,
    ): ResponseEntity<ListUsageResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "List machines (tenant sees its own; super-admin sees all)",
        operationId = "listMachines",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListMachinesResponseDTO::class))],
                )
            ],
        security =
            [SecurityRequirement(name = "tenantSecret"), SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine"],
        produces = ["application/json"],
    )
    fun listMachines(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
        @Parameter(
            description = "",
            schema =
                Schema(
                    allowableValues =
                        ["created", "provisioning", "awaitingLogin", "loggingIn", "ready", "error"]
                ),
        )
        @Valid
        @RequestParam(value = "status", required = false)
        status: MachineStatusDTO?,
    ): ResponseEntity<ListMachinesResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Rebind a machine to a different account (super-admin; internal)",
        operationId = "rebindMachineAccount",
        description =
            """Takes effect on the machine's next login; the current credential is unaffected.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = MachineDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.PUT],
        value = ["/machine/{id}/account"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun rebindMachineAccount(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        rebindAccountRequestDTO: RebindAccountRequestDTO,
    ): ResponseEntity<MachineDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Re-run SSH provisioning (reinstall CA cert + re-apply HTTPS_PROXY)",
        operationId = "reprovisionMachine",
        description =
            """For recovery when a machine was rebuilt or its cert/proxy config was lost.""",
        responses =
            [
                ApiResponse(
                    responseCode = "202",
                    description = "Accepted",
                    content = [Content(schema = Schema(implementation = MachineDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/machine/{id}/reprovision"],
        produces = ["application/json"],
    )
    fun reprovisionMachine(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<MachineDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Start (or restart) this machine's Claude Code login",
        operationId = "startMachineLogin",
        description =
            """Opens a tmux session on the machine, runs Claude Code in normal interactive mode, executes `/login`, and extracts the OAuth URL. Returns a LoginRequest in status `preparing`; it moves to `awaiting-code` once the URL is ready, at which point a login-operator can act on it. Use this for the first login and for re-login after the credential expires or is revoked. Fails with 409 if a login for this machine is already in progress.""",
        responses =
            [
                ApiResponse(
                    responseCode = "202",
                    description = "Accepted",
                    content = [Content(schema = Schema(implementation = LoginRequestDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
                ApiResponse(
                    responseCode = "409",
                    description = "Conflict (precondition not met)",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/machine/{id}/login"],
        produces = ["application/json"],
    )
    fun startMachineLogin(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<LoginRequestDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Rename a machine",
        operationId = "updateMachine",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = MachineDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/machine/{id}"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun updateMachine(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        updateMachineRequestDTO: UpdateMachineRequestDTO,
    ): ResponseEntity<MachineDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
