/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.24.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.ccproxy.api

import app.microteams.ccproxy.model.LineRegistryDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface MtApi {

    @Operation(
        tags = ["transport"],
        summary = "The network paths (MultiPath lines) that lead to the origin",
        operationId = "listLines",
        description =
            """Public: a connector needs this before it can bring up the substrate at all, and it describes routes rather than anything about a tenant. Maintained by hand (`ccproxy.multipath.lines`) — which route is worth keeping is a judgement, not something a health check should decide.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "The line registry",
                    content = [Content(schema = Schema(implementation = LineRegistryDTO::class))],
                )
            ],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        // "/mt/lines"
        value = [PATH_LIST_LINES],
        produces = ["application/json"],
    )
    fun listLines(): ResponseEntity<LineRegistryDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    companion object {
        // for your own safety never directly reuse these path definitions in tests
        const val PATH_LIST_LINES: String = "/mt/lines"
    }
}
