/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.ccproxy.api

import app.microteams.ccproxy.model.CaCertResponseDTO
import app.microteams.ccproxy.model.SshPubkeyResponseDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface ProvisioningApi {

    @Operation(
        tags = ["provisioning"],
        summary = "The MITM CA certificate (PEM)",
        operationId = "getCaCert",
        description =
            """The self-signed CA the machine must trust so Claude Code accepts the intercepted TLS. CCProxy normally installs it over SSH during provisioning; this endpoint exposes it for manual/debug installation.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = CaCertResponseDTO::class))],
                )
            ],
        security =
            [SecurityRequirement(name = "tenantSecret"), SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/provisioning/ca-cert"],
        produces = ["application/json"],
    )
    fun getCaCert(): ResponseEntity<CaCertResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["provisioning"],
        summary = "The SSH public key CCProxy logs in with",
        operationId = "getSshPubkey",
        description =
            """The tenant injects this key into a freshly created machine (as root/authorized user) before registering it with a `host`, so CCProxy can SSH in ONCE to bootstrap the connector (install it and dial in). Returns the OpenSSH single-line public key.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = SshPubkeyResponseDTO::class))],
                )
            ],
        security =
            [SecurityRequirement(name = "tenantSecret"), SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/provisioning/ssh-pubkey"],
        produces = ["application/json"],
    )
    fun getSshPubkey(): ResponseEntity<SshPubkeyResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
