/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.24.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.ccproxy.api

import app.microteams.ccproxy.model.ErrorDTO
import app.microteams.ccproxy.model.SuperadminLoginRequestDTO
import app.microteams.ccproxy.model.SuperadminLoginResponseDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface SuperadminApi {

    @Operation(
        tags = ["superadmin"],
        summary = "Log in as the platform operator; returns a session token",
        operationId = "superadminLogin",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema = Schema(implementation = SuperadminLoginResponseDTO::class)
                            )
                        ],
                ),
                ApiResponse(
                    responseCode = "401",
                    description = "Unauthorized",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        // "/superadmin/login"
        value = [PATH_SUPERADMIN_LOGIN],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun superadminLogin(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        superadminLoginRequestDTO: SuperadminLoginRequestDTO
    ): ResponseEntity<SuperadminLoginResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    companion object {
        // for your own safety never directly reuse these path definitions in tests
        const val PATH_SUPERADMIN_LOGIN: String = "/superadmin/login"
    }
}
