/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.24.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.ccproxy.api

import app.microteams.ccproxy.model.CreateSecretRequestDTO
import app.microteams.ccproxy.model.CreateSecretResponseDTO
import app.microteams.ccproxy.model.CreateTenantRequestDTO
import app.microteams.ccproxy.model.ErrorDTO
import app.microteams.ccproxy.model.ListAuthSecretsResponseDTO
import app.microteams.ccproxy.model.ListTenantsResponseDTO
import app.microteams.ccproxy.model.TenantDTO
import app.microteams.ccproxy.model.UpdateTenantRequestDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface TenantApi {

    @Operation(
        tags = ["tenant"],
        summary = "Create a tenant",
        operationId = "createTenant",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = TenantDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        // "/tenant"
        value = [PATH_CREATE_TENANT],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createTenant(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createTenantRequestDTO: CreateTenantRequestDTO
    ): ResponseEntity<TenantDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["tenant"],
        summary = "",
        operationId = "createTenantSecret",
        description =
            """Mint a new auth secret for the tenant. The plaintext value is returned ONCE (only its hash is stored); the tenant uses it as a Bearer token.""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content =
                        [Content(schema = Schema(implementation = CreateSecretResponseDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        // "/tenant/{id}/secret"
        value = [PATH_CREATE_TENANT_SECRET],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createTenantSecret(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createSecretRequestDTO: CreateSecretRequestDTO,
    ): ResponseEntity<CreateSecretResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["tenant"],
        summary = "Delete a tenant (must have no machines)",
        operationId = "deleteTenant",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
                ApiResponse(
                    responseCode = "409",
                    description = "Conflict (precondition not met)",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        // "/tenant/{id}"
        value = [PATH_DELETE_TENANT],
        produces = ["application/json"],
    )
    fun deleteTenant(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["tenant"],
        summary = "Get a tenant",
        operationId = "getTenant",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = TenantDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        // "/tenant/{id}"
        value = [PATH_GET_TENANT],
        produces = ["application/json"],
    )
    fun getTenant(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<TenantDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["tenant"],
        summary = "List a tenant's auth secrets (metadata only; never the value)",
        operationId = "listTenantSecrets",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema = Schema(implementation = ListAuthSecretsResponseDTO::class)
                            )
                        ],
                )
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        // "/tenant/{id}/secret"
        value = [PATH_LIST_TENANT_SECRETS],
        produces = ["application/json"],
    )
    fun listTenantSecrets(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListAuthSecretsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["tenant"],
        summary = "List tenants",
        operationId = "listTenants",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListTenantsResponseDTO::class))],
                )
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        // "/tenant"
        value = [PATH_LIST_TENANTS],
        produces = ["application/json"],
    )
    fun listTenants(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListTenantsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["tenant"],
        summary = "Revoke one of a tenant's auth secrets",
        operationId = "revokeTenantSecret",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        // "/tenant/{id}/secret/{secretId}"
        value = [PATH_REVOKE_TENANT_SECRET],
        produces = ["application/json"],
    )
    fun revokeTenantSecret(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @PathVariable("secretId")
        secretId: kotlin.Long,
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["tenant"],
        summary = "Update a tenant (rename, suspend, set quota)",
        operationId = "updateTenant",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = TenantDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        // "/tenant/{id}"
        value = [PATH_UPDATE_TENANT],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun updateTenant(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        updateTenantRequestDTO: UpdateTenantRequestDTO,
    ): ResponseEntity<TenantDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    companion object {
        // for your own safety never directly reuse these path definitions in tests
        const val PATH_CREATE_TENANT: String = "/tenant"
        const val PATH_CREATE_TENANT_SECRET: String = "/tenant/{id}/secret"
        const val PATH_DELETE_TENANT: String = "/tenant/{id}"
        const val PATH_GET_TENANT: String = "/tenant/{id}"
        const val PATH_LIST_TENANT_SECRETS: String = "/tenant/{id}/secret"
        const val PATH_LIST_TENANTS: String = "/tenant"
        const val PATH_REVOKE_TENANT_SECRET: String = "/tenant/{id}/secret/{secretId}"
        const val PATH_UPDATE_TENANT: String = "/tenant/{id}"
    }
}
