/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.24.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.ccproxy.api

import app.microteams.ccproxy.model.ListUsageResponseDTO
import app.microteams.ccproxy.model.UsageSummaryDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface UsageApi {

    @Operation(
        tags = ["usage"],
        summary = "Time-bucketed usage history over a window (e.g. 1-minute buckets)",
        operationId = "getUsageSummary",
        description =
            """Returns usage aggregated into fixed-width time buckets — the only billing primitive CCProxy offers. MicroCloud consumes this to do its own billing/quota; CCProxy enforces none.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = UsageSummaryDTO::class))],
                )
            ],
        security =
            [SecurityRequirement(name = "tenantSecret"), SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        // "/usage/summary"
        value = [PATH_GET_USAGE_SUMMARY],
        produces = ["application/json"],
    )
    fun getUsageSummary(
        @Parameter(description = "lower time bound (epoch seconds), inclusive")
        @Valid
        @RequestParam(value = "since", required = false)
        since: kotlin.Long?,
        @Parameter(description = "upper time bound (epoch seconds), exclusive")
        @Valid
        @RequestParam(value = "until", required = false)
        until: kotlin.Long?,
        @Parameter(
            description = "bucket width in seconds (default 60)",
            schema = Schema(defaultValue = "60"),
        )
        @Valid
        @RequestParam(value = "bucket", required = false, defaultValue = "60")
        bucket: kotlin.Int,
        @Parameter(description = "")
        @Valid
        @RequestParam(value = "machineId", required = false)
        machineId: kotlin.Long?,
        @Parameter(description = "super-admin only — scope to one tenant")
        @Valid
        @RequestParam(value = "tenantId", required = false)
        tenantId: kotlin.Long?,
    ): ResponseEntity<UsageSummaryDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["usage"],
        summary = "Usage records (tenant sees its own; super-admin sees all)",
        operationId = "listUsage",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListUsageResponseDTO::class))],
                )
            ],
        security =
            [SecurityRequirement(name = "tenantSecret"), SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        // "/usage"
        value = [PATH_LIST_USAGE],
        produces = ["application/json"],
    )
    fun listUsage(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
        @Parameter(description = "lower time bound (epoch seconds), inclusive")
        @Valid
        @RequestParam(value = "since", required = false)
        since: kotlin.Long?,
        @Parameter(description = "upper time bound (epoch seconds), exclusive")
        @Valid
        @RequestParam(value = "until", required = false)
        until: kotlin.Long?,
        @Parameter(description = "super-admin only — scope to one tenant")
        @Valid
        @RequestParam(value = "tenantId", required = false)
        tenantId: kotlin.Long?,
        @Parameter(description = "")
        @Valid
        @RequestParam(value = "machineId", required = false)
        machineId: kotlin.Long?,
    ): ResponseEntity<ListUsageResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    companion object {
        // for your own safety never directly reuse these path definitions in tests
        const val PATH_GET_USAGE_SUMMARY: String = "/usage/summary"
        const val PATH_LIST_USAGE: String = "/usage"
    }
}
